### ISSUE TITLE
Recommend to checkout my solution

### ISSUE THREAD

**Issue by PhantomYdn** [PkayJava/MBaaS#56]
Hi!
It seems that we are working in the same direction:) Probably, we can combine our efforts?!
Please check out: 
http://orienteer.org 
https://github.com/OrienteerBAP/Orienteer
https://hub.docker.com/r/orienteer/orienteer/

**Comment by PkayJava** [comment]
yeah sure, but it is is a big working.

**Comment by PhantomYdn** [comment]
Sorry - didn't get your previous message.
So, what do you think? Imho, ideas looks close to each other: except that Orienteer is more generic and MBaaS has more customized stuff on java. And Orienteer is already working as SaaS.

**Comment by PkayJava** [comment]
I don't know where to start the integration between these two project.

currently this project is still under development. first version of this project.
it will provide a way to write custom rest json service for mobile
it will provide a way to create custom page (cms), for data entry, report table, according to the specific needed.
currently it support and I still testing

```
Button
CheckBox
CheckBoxMultipleChoice
ColorTextField
DateTextField
DropDownChoice
EmailTextField
Form
HiddenField
ListChoice
ListMultipleChoice
NumberTextField
PasswordTextField
RadioChoice
RangeTextField
RequiredTextField
Select2MultipleChoice
Select2SingleChoice
TextField
TimeTextField
UrlTextField
Table
Label
FileUpload
MultiFileUpload
```

**Comment by PhantomYdn** [comment]
Orienteer has already support of custom rest: through OFunction. User writes OFunction and invocation is available through REST a long with default CRUD operations over data model.
Custom pages are also here: user can create OPage, enter required code for HTML, JavaScript and server side and that's it. It's possible to create dynamic wicket enabled pages.

Regarding list of component. Are you saying that you are allowing dynamically in some WYSIWYG construct page from those component?

**Comment by PkayJava** [comment]
yeah, user able to write freely html, and write business logic of that page.

**Comment by PkayJava** [comment]
I dont have a demo server running yet.

but this is the example of creating a page.

Markup Page : 

```
<!DOCTYPE html>
<html xmlns:wicket="http://wicket.apache.org">
<head>
  <meta charset="utf-8"/>
</head>
<body>
  <p> Page Listing</p>
  <form wicket:id="filterForm">
    <table wicket:id="filterForm_table"/>
  </form>

</body>
</html>
```

Business Logic for that page (Javascript)

```
/*
Page onInitialize
*/
function onInitialize(requestCycle, disk, jdbcTemplate, factory, userModel) { 

  var columns = [
    {
      "tableColumn":"pageId",
      "queryColumn":"page.page_id",
      "classColumn":String.class
    },
    {
      "tableColumn":"title",
      "queryColumn":"page.title",
      "classColumn":String.class
    },
    {
      "tableColumn":"description",
      "queryColumn":"page.description",
      "classColumn":String.class
    }
  ];

  var filterForm = factory.createTable("filterForm", columns, 10);
}

function filterForm__from(jdbcTemplate){
  return DSL.table("page");
}

/*
Page onBeforeRender
*/
function onBeforeRender(requestCycle, disk, jdbcTemplate, factory, userModel) {
}
```

Page will look like.

![screenshot from 2016-06-13 07-40-45](https://cloud.githubusercontent.com/assets/872686/15994879/30f879f0-313a-11e6-8cf1-4da42cceef42.png)

**Comment by PhantomYdn** [comment]
Interesting. Do you have docker image to check that out?

**Comment by PkayJava** [comment]
In the moment no. sorry about that. I wrote a page how to run it.
https://github.com/PkayJava/MBaaS/wiki

**Comment by PkayJava** [comment]
I managed to install on my desktop now, you can access it vai this url

http://skh2016.ddns.net:9080/
uid : admin
pwd : admin

**Comment by PhantomYdn** [comment]
Checked out:) Looks interesting. To make it uniq, I guess, you need to have libraries for Android/IOs to use this backend. Is that what you had in mind?

**Comment by PkayJava** [comment]
I worked on android development to dev sdk(https://github.com/PkayJava/MBaaS-Android-SDK) and a demo app on android. unfortunately most that api are broken now, because because I have add more feature and improvement to mbaas server, but as soon as I complete this cms feature and chat feature on server. I will work on android sdk and demo app again. for iOS i don't have experience on it. I always try to convince my friend to help me on that iOS development :D
