### ISSUE TITLE
data entry student profile

### ISSUE THREAD

**Issue by PkayJava** [PkayJava/MBaaS#68]
![imgpsh_fullsize1a](https://cloud.githubusercontent.com/assets/872686/16183674/e297d558-36de-11e6-99fd-3c80b8e1eb29.png)

**Comment by H-Uddom** [comment]
Done :)

**Comment by PkayJava** [comment]
I still prefer this display data like the following explain

if you see this : 
![a_v](https://cloud.githubusercontent.com/assets/872686/16190668/a76e4bd4-370a-11e6-830d-2d1975d0276f.png)

change to this :
![b_v](https://cloud.githubusercontent.com/assets/872686/16190672/afeef1be-370a-11e6-9c93-b7c62242ce40.png)

**Comment by H-Uddom** [comment]
Student Profile edited
