### ISSUE TITLE
Add new teacher form

### ISSUE THREAD

**Issue by nimolKH** [PkayJava/MBaaS#70]
Please create forms for adding new teacher.

![teacher register 1](https://cloud.githubusercontent.com/assets/20035318/16188883/f541f512-3701-11e6-9186-0762d9d3d092.png)
![teacher register 2](https://cloud.githubusercontent.com/assets/20035318/16188885/f57a6a8c-3701-11e6-96b7-a1166fade310.png)
![teacher register 3](https://cloud.githubusercontent.com/assets/20035318/16188884/f579d4be-3701-11e6-9b20-c6567df05838.png)

**Comment by PkayJava** [comment]
I still prefer this version for display input control.

if you see this : ![a_v](https://cloud.githubusercontent.com/assets/872686/16190607/5c2a503c-370a-11e6-89ea-e412d1c1186f.png)

change to this style : 
![b_v](https://cloud.githubusercontent.com/assets/872686/16190615/6dbc6a6a-370a-11e6-817b-e867e4485f77.png)

**Comment by H-Uddom** [comment]
Done :)
