### ISSUE TITLE
Define Holiday / Apply Holiday / View Full Calendar

### ISSUE THREAD

**Issue by nimolKH** [PkayJava/MBaaS#82]
![define holiday name](https://cloud.githubusercontent.com/assets/20035318/16237456/c1ff093c-3806-11e6-83fc-722d5318065c.png)
![view full calendar](https://cloud.githubusercontent.com/assets/20035318/16237458/c236c6ec-3806-11e6-973f-bb382a82f5f1.png)
![apply holiday](https://cloud.githubusercontent.com/assets/20035318/16237457/c235245e-3806-11e6-9bac-c3b7c4f9b534.png)

**Comment by PkayJava** [comment]
it is depend on this one https://github.com/PkayJava/MBaaS/issues/77, calendar widget is not available yet.
