### ISSUE TITLE
The data is cut off from screen

### ISSUE THREAD

**Issue by H-Uddom** [PkayJava/MBaaS#84]
![untitled](https://cloud.githubusercontent.com/assets/18712687/16259607/ad888410-388d-11e6-94bd-485a30753c78.jpg)

**Comment by H-Uddom** [comment]
When we get many attribute data cant show in one screen it should have horizontal scroll view

**Comment by PkayJava** [comment]
won't fix, alternative solution, is to turn on/off those column
