### ISSUE TITLE
jdbcTemplate.queryForMap is not a function

### ISSUE THREAD

**Issue by H-Uddom** [PkayJava/MBaaS#85]
![error2](https://cloud.githubusercontent.com/assets/18712687/16260007/77930252-388f-11e6-8f3a-baa30785b333.jpg)

**Comment by H-Uddom** [comment]
![error2-1](https://cloud.githubusercontent.com/assets/18712687/16260087/ecef2544-388f-11e6-9011-49fdea0dbf42.jpg)

**Comment by H-Uddom** [comment]
I think because we got the wrong position of parameter. when i change it to 
function onInitialize(requestCycle, disk, jdbcTemplate, factory, pageModel) {
}  

it work correctly.

**Comment by PkayJava** [comment]
fixed default code
