### ISSUE TITLE
Student form - Listing student

### ISSUE THREAD

**Issue by nimolKH** [PkayJava/MBaaS#88]
![manage students](https://cloud.githubusercontent.com/assets/20035318/16327544/64ff78a2-39fa-11e6-8f98-cad76e310e7c.png)

**Comment by nimolKH** [comment]
This form loads student data from database

**Comment by PkayJava** [comment]
<img width="638" alt="screen shot 2016-06-25 at 11 18 42 am" src="https://cloud.githubusercontent.com/assets/872686/16354685/9c115212-3ac6-11e6-9e67-6cc89565dd5d.png">

no need to do this, table already build in search
