### ISSUE TITLE
Main Menu Page

### ISSUE THREAD

**Issue by nimolKH** [PkayJava/MBaaS#90]
![menu](https://cloud.githubusercontent.com/assets/20035318/16362140/9e36b8a6-3bd0-11e6-8186-5d55807a08c6.png)

**Comment by PkayJava** [comment]
:+1:

**Comment by H-Uddom** [comment]
![untitled](https://cloud.githubusercontent.com/assets/18712687/16543603/f16266fc-4106-11e6-9757-8202f3594756.jpg)
